import { readFile } from "node:fs/promises";
import { parseQualifiedTable, qualifiedTableSql, assertSqlIdent } from "./db.js";
import type { MatchSourcePlanJson } from "./types.js";

const TABLE_ALIAS = "vr";

/** Allow only vr."Col" / vr.col with optional repeated ::casts (operator-reviewed plan). */
export function validatePlanSqlFragment(expr: string): boolean {
  const e = expr.trim();
  if (!e.startsWith(`${TABLE_ALIAS}.`)) return false;
  let rest = e.slice(TABLE_ALIAS.length + 1).trim();
  while (rest.length > 0) {
    if (rest.startsWith(".")) {
      rest = rest.slice(1).trim();
      if (rest.startsWith('"')) {
        const end = rest.indexOf('"', 1);
        if (end < 1) return false;
        const inner = rest.slice(1, end);
        if (inner.includes('"')) return false;
        rest = rest.slice(end + 1).trim();
      } else {
        const m = /^[a-zA-Z_][a-zA-Z0-9_]*/.exec(rest);
        if (!m) return false;
        rest = rest.slice(m[0].length).trim();
      }
    } else if (rest.startsWith("::")) {
      const cast =
        /^(::\s*(?:text|integer|date|bigint|uuid|boolean|timestamptz))/i.exec(rest) ||
        /^(::\s*timestamp\s+with\s+time\s+zone)/i.exec(rest);
      if (!cast) return false;
      rest = rest.slice(cast[0].length).trim();
    } else {
      return false;
    }
  }
  return true;
}

function safeExpr(plan: MatchSourcePlanJson, key: string, fallbackTypedNull: string): string {
  const raw = plan.standard_columns[key]?.source_expression ?? null;
  if (raw && validatePlanSqlFragment(raw)) return raw;
  return fallbackTypedNull;
}

function escapeSqlStringLiteral(s: string): string {
  return s.replace(/'/g, "''");
}

/** Normalizes spacing for name/address/city-style text fields. */
function foldWhitespaceNormSql(expr: string): string {
  return `lower(trim(regexp_replace(coalesce((${expr})::text, ''), E'\\\\s+', ' ', 'g')))`;
}

function zip5Sql(zipExpr: string): string {
  return `nullif(substring(regexp_replace(coalesce((${zipExpr})::text, ''), '[^0-9]', '', 'g') from 1 for 5), '')::text`;
}

function isTypedNull(expr: string, cast: string): boolean {
  return expr.trim().toLowerCase() === cast.toLowerCase();
}

/** SELECT list line; adds TODO comment when expression is a typed NULL placeholder. */
function selectListLine(expr: string, alias: string, todoWhenNull: string): string {
  const tr = expr.trim();
  if (/^null::/i.test(tr)) {
    return `  ${expr} as ${alias}, -- TODO: ${todoWhenNull}`;
  }
  return `  ${expr} as ${alias}`;
}

export function emitMatchSourceViewSql(plan: MatchSourcePlanJson, targetQualified: string): string {
  const { schema, table } = parseQualifiedTable(targetQualified);
  assertSqlIdent(schema, "view schema");
  assertSqlIdent(table, "view name");
  const viewSql = qualifiedTableSql(targetQualified);
  const fromQt = qualifiedTableSql(plan.canonical_table);

  const voterId = safeExpr(plan, "voter_id", "null::text");
  const firstName = safeExpr(plan, "first_name", "null::text");
  const lastName = safeExpr(plan, "last_name", "null::text");
  const birthDate = safeExpr(plan, "birth_date", "null::date");
  const birthYear = safeExpr(plan, "birth_year", "null::integer");
  const address = safeExpr(plan, "address", "null::text");
  const city = safeExpr(plan, "city", "null::text");
  const county = safeExpr(plan, "county", "null::text");
  const state = safeExpr(plan, "state", "null::text");
  const zip = safeExpr(plan, "zip", "null::text");

  const firstNorm = isTypedNull(firstName, "null::text") ? "null::text" : foldWhitespaceNormSql(firstName);
  const lastNorm = isTypedNull(lastName, "null::text") ? "null::text" : foldWhitespaceNormSql(lastName);
  const addrNorm = isTypedNull(address, "null::text") ? "null::text" : foldWhitespaceNormSql(address);
  const cityNorm = isTypedNull(city, "null::text") ? "null::text" : foldWhitespaceNormSql(city);
  const countyNorm = isTypedNull(county, "null::text") ? "null::text" : foldWhitespaceNormSql(county);

  const zip5 = isTypedNull(zip, "null::text") ? "null::text" : zip5Sql(zip);

  const ward = safeExpr(plan, "ward", "null::text");
  const precinct = safeExpr(plan, "precinct", "null::text");
  const district = safeExpr(plan, "district", "null::text");
  const wardNorm = isTypedNull(ward, "null::text") ? "null::text" : foldWhitespaceNormSql(ward);
  const precinctNorm = isTypedNull(precinct, "null::text") ? "null::text" : foldWhitespaceNormSql(precinct);
  const districtNorm = isTypedNull(district, "null::text") ? "null::text" : foldWhitespaceNormSql(district);

  const updRaw = plan.standard_columns.source_updated_at?.source_expression ?? null;
  const sourceUpdated =
    updRaw && validatePlanSqlFragment(updRaw)
      ? `${updRaw.replace(/::timestamptz\s*$/i, "")}::timestamptz`
      : "now()::timestamptz";

  const metaTable = escapeSqlStringLiteral(plan.canonical_table);
  const meta = `jsonb_build_object('source_table', '${metaTable}')`;

  const header = [
    "-- Generated by voter-file-matcher (--emit-match-source-sql / --write-match-source-sql).",
    "-- Review carefully before applying in any environment.",
    "-- No voter row data was read — only plan JSON and identifier metadata.",
    "",
  ].join("\n");

  const selectLines = [
    selectListLine(voterId, "voter_id", "map voter_id from canonical table"),
    selectListLine(firstName, "first_name", "map first name"),
    selectListLine(lastName, "last_name", "map last name"),
    selectListLine(firstNorm, "first_name_norm", "derived from first_name"),
    selectListLine(lastNorm, "last_name_norm", "derived from last_name"),
    selectListLine(birthDate, "birth_date", "map date of birth"),
    selectListLine(birthYear, "birth_year", "map birth year"),
    selectListLine(address, "address", "map street / mailing address"),
    selectListLine(addrNorm, "address_norm", "derived from address"),
    selectListLine(city, "city", "map city"),
    selectListLine(cityNorm, "city_norm", "derived from city"),
    selectListLine(county, "county", "map county"),
    selectListLine(countyNorm, "county_norm", "derived from county"),
    selectListLine(state, "state", "map state"),
    selectListLine(zip, "zip", "map ZIP / postal"),
    selectListLine(zip5, "zip5", "derived from zip"),
    selectListLine(ward, "ward", "map ward for WARD reporting"),
    selectListLine(wardNorm, "ward_norm", "derived from ward"),
    selectListLine(precinct, "precinct", "map precinct"),
    selectListLine(precinctNorm, "precinct_norm", "derived from precinct"),
    selectListLine(district, "district", "map district"),
    selectListLine(districtNorm, "district_norm", "derived from district"),
    selectListLine(sourceUpdated, "source_updated_at", "map updated_at or use now()"),
    selectListLine(meta, "source_metadata", "extend jsonb metadata if needed"),
  ];

  const lines = [
    header,
    `create or replace view ${viewSql} as`,
    `select`,
    selectLines.join(",\n"),
    `from ${fromQt} ${TABLE_ALIAS};`,
    "",
  ];

  return lines.join("\n");
}

function escapeReg(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Remove line and block comments for static analysis only. */
export function stripSqlComments(sql: string): string {
  let s = sql;
  while (true) {
    const i = s.indexOf("/*");
    if (i < 0) break;
    const j = s.indexOf("*/", i + 2);
    if (j < 0) throw new Error("Unclosed block comment in SQL file.");
    s = `${s.slice(0, i)} ${s.slice(j + 2)}`;
  }
  const outLines: string[] = [];
  for (const line of s.split("\n")) {
    const idx = line.indexOf("--");
    outLines.push(idx >= 0 ? line.slice(0, idx) : line);
  }
  return outLines.join("\n");
}

function viewReferenceVariants(schema: string, table: string): string[] {
  return [
    `"${schema}"."${table}"`,
    `${schema}.${table}`,
    `"${schema}".${table}`,
    `${schema}."${table}"`,
  ];
}

/**
 * Ensures SQL is a single CREATE OR REPLACE VIEW for the expected target, with no destructive DML/DDL.
 * Does not execute.
 */
export function assertSafeMatchSourceViewSql(sql: string, targetQualified: string): void {
  const stripped = stripSqlComments(sql);
  if (
    /\b(drop|delete|update|insert|truncate|alter\b|grant|revoke|copy\s|execute|call|create\s+table|create\s+function|create\s+index|create\s+database|create\s+schema|references|constraint)\b/i.test(
      stripped
    )
  ) {
    throw new Error("SQL failed safety gate: disallowed keyword detected.");
  }
  const parts = stripped
    .split(";")
    .map((p) => p.trim())
    .filter((p) => p.length > 0);
  if (parts.length !== 1) {
    throw new Error("Expected exactly one SQL statement (CREATE OR REPLACE VIEW …); check semicolons.");
  }
  const one = parts[0]!;
  if (!/^\s*create\s+or\s+replace\s+view\b/i.test(one)) {
    throw new Error('SQL must be a single CREATE OR REPLACE VIEW statement.');
  }
  const { schema, table } = parseQualifiedTable(targetQualified);
  const variants = viewReferenceVariants(schema, table);
  const rest = one.replace(/^\s*create\s+or\s+replace\s+view\s+/i, "").trim();
  const matched = variants.some((v) => {
    const re = new RegExp(`^${escapeReg(v)}\\s+as\\b`, "i");
    return re.test(rest);
  });
  if (!matched) {
    throw new Error(
      `VIEW name in SQL must match target ${targetQualified} (allowed identifier variants: ${variants.join(", ")}).`
    );
  }
}

export async function loadMatchSourcePlan(path: string): Promise<MatchSourcePlanJson> {
  const raw = await readFile(path, "utf8");
  const j = JSON.parse(raw) as MatchSourcePlanJson;
  if (!j || typeof j !== "object" || !j.standard_columns) {
    throw new Error("Invalid match source plan JSON.");
  }
  return j;
}

export async function readSqlFile(path: string): Promise<string> {
  return readFile(path, "utf8");
}
